### ISSUE TITLE
对于不在文件里character和punctuation的中文字符能不能生成？

### ISSUE THREAD

**Issue by yanziwu621** [xxyQwQ/metascript#3]
如题。

**Comment by xxyQwQ** [comment]
不能，模型只在常用字上进行了训练
支持更多字符需要扩大数据集重新训练模型

**Comment by ruobing-yang** [comment]
请问如果要使用我自己的writer数据进行训练，writer文件中的字与template中的字要保持一致吗？能否仅用少量的writer汉字生成您使用的三千多个template汉字？

**Comment by xxyQwQ** [comment]
> 请问如果要使用我自己的writer数据进行训练，writer文件中的字与template中的字要保持一致吗？能否仅用少量的writer汉字生成您使用的三千多个template汉字？

(1) 训练时只要保证字的ID一一对应即可 (2) 没有看懂你的问题，template只是作为字形参考，不是生成目标

**Comment by ruobing-yang** [comment]
我的意思是，您在论文中说，训练集使用的是 CASIAHWDB-1.1中300个作家的字迹，包括了3755个常见字，能够生成的字符也仅限于这3755个汉字。我用自己的笔迹输入试了一下觉得模仿的效果不是很好，所以想试着自己构建一个数据集来训练，但是我的数据集可能只包含了20个人的笔迹，只包含了一百多个常用字，这种情况下，模型还是可以生成3755个常见字吗？
