### ISSUE TITLE
可以提供训练集参数文件吗？

### ISSUE THREAD

**Issue by ruobing-yang** [xxyQwQ/metascript#5]
你好，请问可以提供一下文中训练集训练好的参数文件吗？我自己的电脑跑时间太长了

**Comment by xxyQwQ** [comment]
我们已经提供了模型文件，请参考 `README.md` 中的 `Inference` 章节

> We provide a pre-trained model [here](https://pan.baidu.com/s/1UGHPKFVSvRj2QY_PbSjJGQ?pwd=1024), whose reference_count is 4. Notice that reference_count means the number of reference images used by the model, which should be consistent with your model setting. If you provide more reference images than this number, only a subset of them will be actually used. Do not modify it unless you know what you are doing.
